// <auto-generated />
namespace Recruiter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Mergedwork : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mergedwork));
        
        string IMigrationMetadata.Id
        {
            get { return "201902071436174_Mergedwork"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
